// Generated by CoffeeScript 1.9.3
(function() {
  var CompositeDisposable, GithubTasks, GithubTasksView;

  GithubTasksView = require('./github-tasks-view');

  CompositeDisposable = require('atom').CompositeDisposable;

  module.exports = GithubTasks = {
    githubTasksView: null,
    modalPanel: null,
    subscriptions: null,
    activate: function(state) {
      this.githubTasksView = new GithubTasksView(state.githubTasksViewState);
      this.modalPanel = atom.workspace.addModalPanel({
        item: this.githubTasksView.getElement(),
        visible: false
      });
      this.subscriptions = new CompositeDisposable;
      return this.subscriptions.add(atom.commands.add('atom-workspace', {
        'github-tasks:toggle': (function(_this) {
          return function() {
            return _this.toggle();
          };
        })(this)
      }));
    },
    deactivate: function() {
      this.modalPanel.destroy();
      this.subscriptions.dispose();
      return this.githubTasksView.destroy();
    },
    serialize: function() {
      return {
        githubTasksViewState: this.githubTasksView.serialize()
      };
    },
    toggle: function() {
      console.log('GithubTasks was toggled!');
      if (this.modalPanel.isVisible()) {
        return this.modalPanel.hide();
      } else {
        return this.modalPanel.show();
      }
    }
  };

}).call(this);
